apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: nginx:latest
        name: guestbook-ui
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: '100Mi'
            cpu: '100m'
          limits:
            memory: '200Mi'
            cpu: '200m'
        securityContext:
          privileged: false
          #readOnlyRootFilesystem: false # guestbook neet to write to /var/run/apache2/apache2.pid
          allowPrivilegeEscalation: false